language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.300
services:
  - docker
branches:
  only:
    - master
    - dev
script:
  - dotnet build
  - dotnet test FakeSender.Api.Tests
deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push framebassman/fake-sender
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always