language: csharp
dist: trusty
sudo: required
mono: none
before_install:
  - curl -o dotnet-install.sh https://dot.net/v1/dotnet-install.sh
  - /bin/bash dotnet-install.sh --channel 2.2 --version latest
services:
  - docker
branches:
  only:
    - /.*/
script:
  - dotnet build
  - dotnet test FakeSender.Api.Tests
  - dotnet test FakeSender.Tests
deploy:
  provider: script
  script: bash Scripts/deploy.sh
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
