language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0-preview2-006497
services:
  - docker
branches:
  only:
    - master
    - dev
script:
  - dotnet build
  - dotnet test FakeSender.Api.Tests
deploy:
  provider: script
  script: bash Scripts/deploy.sh
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always