language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1
services:
  - docker
branches:
  only:
    - /.*/
script:
  - dotnet build
  - dotnet test FakeSender.Api.Tests
  - dotnet test FakeSender.Tests
deploy:
  provider: script
  script: bash Scripts/deploy.sh
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
