language: csharp
dist: trusty
sudo: required
mono: none
before_install:
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo add-apt-repository universe
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.2
services:
  - docker
branches:
  only:
    - /.*/
script:
  - dotnet build
  - dotnet test FakeSender.Api.Tests
  - dotnet test FakeSender.Tests
deploy:
  provider: script
  script: bash Scripts/deploy.sh
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
