language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.2
services:
  - docker
branches:
  only:
    - /.*/
script:
  - dotnet build
  - dotnet test FakeSender.Api.Tests
  - make build start-test
  - bash Scripts/wait-until-service-is-up.sh
  - dotnet test FakeSender.Tests
  - make stop
deploy:
  provider: script
  script: bash Scripts/deploy.sh
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
