// <auto-generated />
using FakeSender.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace FakeSender.Api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20181008155438_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("FakeSender.Api.Models.ApnsQuery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplePassTypeId");

                    b.Property<string>("PushToken");

                    b.HasKey("Id");

                    b.ToTable("ApnsQueryBox");
                });

            modelBuilder.Entity("FakeSender.Api.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Attachments");

                    b.Property<string>("Html");

                    b.Property<string>("Subject");

                    b.Property<string>("To");

                    b.HasKey("Id");

                    b.ToTable("EmailBox");
                });

            modelBuilder.Entity("FakeSender.Api.Models.Sms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message");

                    b.Property<string>("To");

                    b.HasKey("Id");

                    b.ToTable("SmsBox");
                });
#pragma warning restore 612, 618
        }
    }
}
